"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-@e3_f$45btsmgsxlsrs0cemgcnq@htw+*)3r%a1z&mm2ot^-ig"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    # The Django built-in application for controling login, logout in Django
    # it authenticate users for us
    # List of all the built-in URLs from Django's auth app:
    # 0. admin/
    # 1. login/ [name='login']
    # 2. logout/ [name='logout']
    # 3. password_change/ [name='password_change']
    # 4. password_change/done/ [name='password_change_done']
    # 5. password_reset/ [name='password_reset']
    # 6. password_reset/done/ [name='password_reset_done']
    # 7. reset/<uidb64>/<token>/ [name='password_reset_confirm']
    # 8. reset/done/ [name='password_reset_complete']
    "django.contrib.auth",
    
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Installed 3rd party apps by Edmon
    "debug_toolbar",
    # cripsy-form is used to improve the UI of the form
    "crispy_forms",
    "crispy_tailwind",

    # Created Apps by Edmon.
    # The default website for the project
    "website",
    # "users"; the app that will handle users' sign-in, sign-up, registeration
    # and creating new accounts on the website
    "users",  # This is the "Sign Up Page" for creating new user accounts
]

MIDDLEWARE = [
    # Middlewares Added by Edmon
    "debug_toolbar.middleware.DebugToolbarMiddleware",


    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'v2_documents_managment_project_db1',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Custom Configurations and Settings addedy by Edmon:

# Configure Internal IPs
# The Debug Toolbar is shown only if your IP address is listed
# in Django’s INTERNAL_IPS setting. This means that for local development,
# you must add "127.0.0.1" to INTERNAL_IPS. You’ll need to create
# this setting if it doesn’t already exist in your settings module:

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]


# Telling Django to use the crispy form template for tailwind-css library
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"



AUTHENTICATION_BACKENDS = [

    # Log using the built-in Django
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # Login Using Things like Email address, Gmail Account, Facebook Account, Github Account, and Others
    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',

]

# Django defaults to an SMTP email backend that requires some configuration. 
# To test the password reset flow locally, we can update the django_project/settings.py 
# file to output emails to the console instead. Add this one line to the bottom of the file.
# 
# django_project/settings.py
# 
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend" # new
# Finally, we can try the Password Reset page again at
#  http://127.0.0.1:8000/accounts/password_reset/. 
# Enter the email address for your regular user account and click the 
# "Change My Password" button. It will redirect you to the password reset sent page.
# 
#
# For security reasons, Django will not provide any notification whether you 
# entered an email that exists in the database or not.
#  But if you look in your terminal/console now, 
# you can see the contents of the email outputted there.
#
# Content-Type: text/plain; charset= "utf-8"
# MIME-Version: 1.0
# Content-Transfer-Encoding: 8bit
# Subject: Password reset on 127.0.0.1:8000
# From: webmaster@localhost
# To: testuser@email.com
# Date: Fri, 26 Jan 2024 20:04:32 -0000
# Message-ID: <170629947287.95157.11297370611002899863@1.0.0.127.in-addr.arpa>
#
#
# You're receiving this email because you requested a password reset for your 
# user account at 127.0.0.1:8000.
#
# Please go to the following page and choose a new password:
#
# http://127.0.0.1:8000/accounts/reset/Mg/c1fefk-40c35272edd84fcb73f64d2b4ebd0e8f/
#
# Your username, in case you've forgotten: testuser
#
# Thanks for using our site!
#
# The 127.0.0.1:8000 team
#
# 
#
# -------------------------------------------------------------------------------
# Copy the unique URL from your console into your web browser. 
# It will cryptographically confirm your identity and take you to the
# Password Reset Confirmation page at http://127.0.0.1:8000/accounts/reset/Mg/set-password/.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# "ACCOUNT_AUTHENTICATION_METHOD" (="username" | "email" | "username_email")
# Specifices the login method to use - whether the user logs in by entering their username, e-mail address,
# or either one of both. Setting this to "email" requires ACCOUNT_EMAIL_REQUIRED=True
ACCOUNT_AUTHENTICATION_METHOD = "username_email"


# This setting confirms the User's email account as soon as the user clicks the link on the email address
# thier acccount is confirmed.
ACCOUNT_CONFIRM_EMAIL_ON_GET = True


# This allows users to sign up using their email account
ACCOUNT_EMAIL_REQUIRED = True

# Account email verification: This option can be used to set whether an email verification
# is necessary for a user to log in after he registers an account. You can use ‘mandatory’
# to block a user from logging in until the email gets verified. You can set options
# for sending the email but allowing the user to log in without an email.
# You can also set none to send no verification email. (Not Recommended)
# Determines the e-mail verificaiton method during signup - choose one of
# "mandatory", "optional" or "none"
ACCOUNT_EMAIL_VERIFICATION = "mandatory"


# Email confirmation expiry: Sets the number of days within which 
# an account should be activated.
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 7


# Login Attempt Limit: This is an important feature which can be used to prevent
# brute force attacks on the user login page on your website.
# The maximum number of login attempts can be set,
# and the user gets blocked from logging back in until a timeout.
# This feature makes use of ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT setting.
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5

# The default behavior is not log users in and to redirect them to
# "ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL".
# By changing this setting to "True", users will automatically be logged in once they
# confirm their email address. 
# Note, however that this only works when confirming the email
# address "immediately after signing up", assuming users didn't close their browser or used some sort of
# private browsing mode.
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# ACCOUNTLOGOUT_ON_GET ; determines whether or not the user is 
# automatically logged out by a GET request
# GET is not designed to modify the server state, and in this case it can be dangerous.
ACCOUNT_LOGOUT_ON_GET = True

# ACCOUNT_LOGIN_ON_PASSWORD_RESET (False)
# By changing this setting to "True", users will automatically be logged in once they have reset their
# password. By default their are redirected to the password reset done page.
# Note 3: It is better to leave this setting to "False" or on default setting because we want
# to check and make sure the user's new password works and they can access the website once they change
# to new password or once they reset their password.
ACCOUNT_LOGIN_ON_PASSWORD_RESET = False


# Login and Logout URL redirection: When user logs in or logs out,
# you might want to redirect the user to a particular URL or page and
# the below settings can be used to set that URL.
# By default, allauth redirects login to /accounts/profile/ URL
# and logout to the localhost:8000 or any localhost homepage.

# These are the default login and logout redirects for allauths.
# ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login/'
# LOGIN_REDIRECT_URL = '/accounts/email/'

# These are the custom login and logout redirects for allauths for
# managming users accounts.
LOGIN_REDIRECT_URL = "home"
ACCOUNT_LOGOUT_REDIRECT_URL = "home"


# ACCOUNT_PRESERVE_USERNAME_CASING = False
# This setting determines whether the username is stored in lowercase (False)
#  or whether it its casing
# to be preserved (True).
# Note 1: Setting this to "False" allows us to have Users' username in all lowercase letters.
ACCOUNT_PRESERVE_USERNAME_CASING = False


# ACCOUNT_SESSION_REMEMBER = False
# Controls the life time of the session. Set to "None" to ask the user ("Remember me?"),
# "False" to not remember, and "True" to always remember
ACCOUNT_SESSION_REMEMBER = False


# ACCOUNT_USERNAME_BLACKLIST (=[])
# "ACCOUNT_USERNAME_BLACKLIST" is a list of usernames that can't be used by users on the website
# or portal web app
ACCOUNT_USERNAME_BLACKLIST = [
    "edmon",
    "edmontheprogrammer",
    "god",
    "admin",
    "administrator",
    "superuser",
    "createsuperuser"]

# ACCOUNT_USERNAME_MIN_LENGTH (=1)
# An integer specifying the minimum allowed length of a username
ACCOUNT_USERNAME_MIN_LENGTH = 3

# Login Attempt Limit timeout: This setting should be used with
# setting ACCOUNT_LOGIN_ATTEMPTS_LIMIT . The value set is in seconds from the last
# unsuccessful login attempt. Please note that this does not protect admin login.

# ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 86400 # 1 day in seconds

# Sets the ID of your site's URL.
# The Django Project or Django Framework can have multiple websites.
# "SITE_ID" is the unique identifier for each web app or each website that you create.
# "SITE_ID" is the the primary key for each Django web app you create.
# This line identifies the "portal" web app with a site id of 1 "SITE_ID = 1"
SITE_ID = 1
